.DEFAULT:
all: flip_equivalent_binary_trees.o
	g++ -o flip_equivalent_binary_trees flip_equivalent_binary_trees.o

flip_equivalent_binary_trees.o: flip_equivalent_binary_trees.cpp
	g++ -c flip_equivalent_binary_trees.cpp -std=c++11

clean:
	rm flip_equivalent_binary_trees
	rm *.o
