.DEFAULT:
all: average_of_levels_in_binary_tree.o
	g++ -o average_of_levels_in_binary_tree average_of_levels_in_binary_tree.o

average_of_levels_in_binary_tree.o: average_of_levels_in_binary_tree.cpp
	g++ -c average_of_levels_in_binary_tree.cpp -std=c++11

clean:
	rm average_of_levels_in_binary_tree
	rm *.o
