.DEFAULT:
all: kth_smallest_element_in_a_bst.o
	g++ -o kth_smallest_element_in_a_bst kth_smallest_element_in_a_bst.o

kth_smallest_element_in_a_bst.o: kth_smallest_element_in_a_bst.cpp
	g++ -c kth_smallest_element_in_a_bst.cpp -std=c++11

clean:
	rm kth_smallest_element_in_a_bst
	rm *.o
