.DEFAULT:
all: n_ary_tree_preorder_traversal.o
	g++ -o n_ary_tree_preorder_traversal n_ary_tree_preorder_traversal.o

n_ary_tree_preorder_traversal.o: n_ary_tree_preorder_traversal.cpp
	g++ -c n_ary_tree_preorder_traversal.cpp -std=c++11

clean:
	rm n_ary_tree_preorder_traversal
	rm *.o
