.DEFAULT:
all: minimum_falling_path_sum_2.o
	g++ -o minimum_falling_path_sum_2 minimum_falling_path_sum_2.o

minimum_falling_path_sum_2.o: minimum_falling_path_sum_2.cpp
	g++ -c minimum_falling_path_sum_2.cpp -std=c++11

clean:
	rm minimum_falling_path_sum_2
	rm *.o
