.DEFAULT:
all: maximum_profit_in_job_scheduling.o
	g++ -o maximum_profit_in_job_scheduling maximum_profit_in_job_scheduling.o

maximum_profit_in_job_scheduling.o: maximum_profit_in_job_scheduling.cpp
	g++ -c maximum_profit_in_job_scheduling.cpp -std=c++11

clean:
	rm maximum_profit_in_job_scheduling
	rm *.o
