.DEFAULT:
all: maximum_level_sum_of_a_binary_tree.o
	g++ -o maximum_level_sum_of_a_binary_tree maximum_level_sum_of_a_binary_tree.o

maximum_level_sum_of_a_binary_tree.o: maximum_level_sum_of_a_binary_tree.cpp
	g++ -c maximum_level_sum_of_a_binary_tree.cpp -std=c++11

clean:
	rm maximum_level_sum_of_a_binary_tree
	rm *.o
