.DEFAULT:
all: best_time_to_buy_and_sell_stock.o
	g++ -o best_time_to_buy_and_sell_stock best_time_to_buy_and_sell_stock.o

best_time_to_buy_and_sell_stock.o: best_time_to_buy_and_sell_stock.cpp
	g++ -c best_time_to_buy_and_sell_stock.cpp -std=c++11

clean:
	rm best_time_to_buy_and_sell_stock
	rm *.o
