.DEFAULT:
all: minimum_ascii_delete_sum_for_two_strings.o
	g++ -o minimum_ascii_delete_sum_for_two_strings minimum_ascii_delete_sum_for_two_strings.o

minimum_ascii_delete_sum_for_two_strings.o: minimum_ascii_delete_sum_for_two_strings.cpp
	g++ -c minimum_ascii_delete_sum_for_two_strings.cpp -std=c++11

clean:
	rm minimum_ascii_delete_sum_for_two_strings
	rm *.o
