.DEFAULT:
all: combination_sum_iv.o
	g++ -o combination_sum_iv combination_sum_iv.o

combination_sum_iv.o: combination_sum_iv.cpp
	g++ -c combination_sum_iv.cpp -std=c++11

clean:
	rm combination_sum_iv
	rm *.o
