.DEFAULT:
all: all_elements_in_two_binary_search_trees.o
	g++ -o all_elements_in_two_binary_search_trees all_elements_in_two_binary_search_trees.o

all_elements_in_two_binary_search_trees.o: all_elements_in_two_binary_search_trees.cpp
	g++ -c all_elements_in_two_binary_search_trees.cpp -std=c++11

clean:
	rm all_elements_in_two_binary_search_trees
	rm *.o
