.DEFAULT:
all: binary_tree_level_order_traversal.o
	g++ -o binary_tree_level_order_traversal binary_tree_level_order_traversal.o

binary_tree_level_order_traversal.o: binary_tree_level_order_traversal.cpp
	g++ -c binary_tree_level_order_traversal.cpp -std=c++11

clean:
	rm binary_tree_level_order_traversal
	rm *.o
