.DEFAULT:
all: valid_palindrome_2.o
	g++ -o valid_palindrome_2 valid_palindrome_2.o

valid_palindrome_2.o: valid_palindrome_2.cpp
	g++ -c valid_palindrome_2.cpp -std=c++11

clean:
	rm valid_palindrome_2
	rm *.o
