.DEFAULT:
all: minimum_distance_to_type_a_word_using_two_fingers.o
	g++ -o minimum_distance_to_type_a_word_using_two_fingers minimum_distance_to_type_a_word_using_two_fingers.o

minimum_distance_to_type_a_word_using_two_fingers.o: minimum_distance_to_type_a_word_using_two_fingers.cpp
	g++ -c minimum_distance_to_type_a_word_using_two_fingers.cpp -std=c++11

clean:
	rm minimum_distance_to_type_a_word_using_two_fingers
	rm *.o
