.DEFAULT:
all: peak_index_in_a_mountain_array.o
	g++ -o peak_index_in_a_mountain_array peak_index_in_a_mountain_array.o

peak_index_in_a_mountain_array.o: peak_index_in_a_mountain_array.cpp
	g++ -c peak_index_in_a_mountain_array.cpp -std=c++11

clean:
	rm peak_index_in_a_mountain_array
	rm *.o
