.DEFAULT:
all: max_area_of_island.o
	g++ -o max_area_of_island max_area_of_island.o

max_area_of_island.o: max_area_of_island.cpp
	g++ -c max_area_of_island.cpp -std=c++11

clean:
	rm max_area_of_island
	rm *.o
