.DEFAULT:
all: best_time_to_buy_and_sell_stock_with_transaction_fee.o
	g++ -o best_time_to_buy_and_sell_stock_with_transaction_fee best_time_to_buy_and_sell_stock_with_transaction_fee.o

best_time_to_buy_and_sell_stock_with_transaction_fee.o: best_time_to_buy_and_sell_stock_with_transaction_fee.cpp
	g++ -c best_time_to_buy_and_sell_stock_with_transaction_fee.cpp -std=c++11

clean:
	rm best_time_to_buy_and_sell_stock_with_transaction_fee
	rm *.o
